// src/Sites/twitch.tv/Components/BanSlider.tsx
import React, { PointerEvent, useState } from 'react';
import Restore from '@material-ui/icons/Restore';
import SvgIcon from '@material-ui/core/SvgIcon';

const minVal = 40.0;
const delVal = 80.0;
const maxVal = 300.0;
const maxSeconds = 1209600.0;

const numberToTime = (val: number): string => {
	if ( val < 60 ) {
		return ( `${Math.round(val)} seconds` );
	} else if ( val < 60*60 ) {
		return ( `${Math.round(val/60)} minutes` );
	} else if ( val < 60*60*24 ) {
		return ( `${Math.round(val/(60*60))} hours` );
	} else {
		return ( `${Math.round(val/(60*60*24))} days` );
	}
};

class sliderData {
	command = '';
	text = '';
	time = 0;
	unbanVis = 0;
	color = '';
	pos = '0px';

	constructor(pos: number) {
		this.pos = `${pos}px`;

		if (pos < -40) {
			this.command = '/unban {user}';
			this.unbanVis = 1;
		} else if ( pos < minVal ) {
			return;
		} else if ( pos < delVal ) {
			this.command = '/delete {id}';
			this.text = 'Delete';
			this.color = '#FFFF00';
		} else if ( pos < maxVal ) {
			const time = Math.pow((pos + 0.25*maxVal - delVal)/(1.25*maxVal - delVal), 10)*maxSeconds;

			this.command = `/timeout {user} ${Math.round(time)}`;
			this.text = String(numberToTime(time));
			this.color = '#FFA500';
		} else {
			this.command = '/ban {user}';
			this.text = 'Ban';
			this.color = '#C40000';
		}
	}
}

export function BanSlider({onRelease}: BanSlider.props): JSX.Element {

	const [data, setData] = useState(new sliderData(0));
	const [tracking, setTracking] = useState(false);
	const [initial, setInitial] = useState(0);

	const handleDown = 	(e: PointerEvent) => {
		e.stopPropagation();
		setInitial(e.pageX);
		setTracking(true);
		(e.target as HTMLElement).setPointerCapture(e.pointerId);
	};

	const handleRelease = (e: PointerEvent): void => {
		setTracking(false);

		if ( !!data.command ) { onRelease(data); }

		e.pageX = initial;
		update(e);

		(e.target as HTMLElement).releasePointerCapture(e.pointerId);
	};

	const update = (e: PointerEvent): void => {
		e.preventDefault();

		const calcPos = Math.max(Math.min(e.pageX - initial, maxVal), -50);

		setData(new sliderData(calcPos));
		(e.target as HTMLElement).offsetParent!.parentElement!.style.transform = `translateX(${calcPos}px)`;
	};

	return (
		<div className='outer'>
			<div
				className='behind'
				style={{
					backgroundColor: data.color,
					width: data.pos,
					transform: `translateX(-${data.pos})`
				}}>
				<span className='text'>
					{data.text}
				</span>
			</div>
			<div className='grabbable-outer'
				title='7TV Moderation slider'
				onPointerDown={ handleDown }
				onPointerUp={ handleRelease }
				onPointerMove={	(e: PointerEvent) => { if (tracking) { update(e); }} }
				>
				<div className='grabbable-inner'>
					<div className='dots'/>
				</div>
			</div>
			<div className='unban-icon'
				style={{
					opacity: data.unbanVis
					}}>
				<SvgIcon component={Restore} />
			</div>
		</div>
	);
}

export namespace BanSlider {
	export interface props {
		onRelease: (x: sliderData) => void;
	}
}

// src/site/twitch.tv/modules/chat/components/BanSlider.vue
<template>
	<div
		v-if="shouldModerate(props.msg)"
		class="seventv-ban-slider"
		:style="{
			transform: 'translateX(' + data.pos + ')',
			transition: transition ? 'transform 0.3s ease' : 'none',
			boxShadow: tracking ? 'black 0px 0.1rem 0.2rem' : 'none',
		}"
	>
		<div class="ban-background" :style="{ backgroundColor: data.color, width: data.pos }">
			<span class="text" :style="{ opacity: data.banVis }">
				{{ data.text }}
			</span>
		</div>
		<div class="grabbable-wrapper">
			<div class="grabbable-outer" @pointerdown="handleDown" @pointerup="handleRelease" @pointermove="update">
				<div class="grabbable-inner">
					<div class="dots" />
				</div>
			</div>
		</div>
		<!-- The wrapped object-->
		<slot />
		<div class="unban-background" :style="{ width: 'calc(-1 *' + data.pos + ')' }">
			<span class="text" :style="{ opacity: data.unbanVis }"> Unban </span>
		</div>
	</div>
	<slot v-else />
</template>

<script setup lang="ts">
import { ref } from "vue";
import { sliderData, maxVal, executeModAction, shouldModerate } from "./BanSliderBackend";

const props = defineProps<{
	msg: Twitch.ChatMessage;
}>();

const transition = ref(false);
const tracking = ref(false);

const data = ref(new sliderData(0));
let initial = 0;

const handleDown = (e: PointerEvent) => {
	e.stopPropagation();
	initial = e.pageX;
	tracking.value = true;
	(e.target as HTMLElement).setPointerCapture(e.pointerId);
};

const handleRelease = (e: PointerEvent): void => {
	tracking.value = false;

	if (data.value.command) {
		executeModAction(data.value.command, props.msg.user.userLogin, props.msg.id);
	}

	transition.value = true;
	setTimeout(() => (transition.value = false), 300);

	data.value = new sliderData(0);
	(e.target as HTMLElement).releasePointerCapture(e.pointerId);
};

const update = (e: PointerEvent): void => {
	if (!tracking.value) return;
	e.preventDefault();

	const calcPos = Math.max(Math.min(e.pageX - initial, maxVal), -60);

	data.value = new sliderData(calcPos);
};
</script>

<style scoped lang="scss">
.transition {
	transition: transform 0.3s ease;
}

%background {
	position: absolute;
	top: 0;
	box-shadow: inset 0.1em 0.1em 0.4em black;
	display: flex;
	align-items: center;
	overflow: hidden;
	height: 100%;
	transition: background-color 0.2s ease;
	.text {
		position: relative;
		white-space: nowrap;
		width: 100%;
		text-align: center;
		text-shadow: 0.1em 0 0.2rem var(--color-background-body), 0 0.1em 0.2rem var(--color-background-body),
			-0.1em 0 0.2rem var(--color-background-body), 0 -0.1em 0.2rem var(--color-background-body);
		transition: opacity 0.2s ease;
	}
}
.unban-background {
	@extend %background;
	left: 100%;
	background-color: green;
}

.ban-background {
	@extend %background;
	right: 100%;
}

.grabbable-wrapper {
	width: 0;
	height: 100%;
	position: absolute;
	.grabbable-outer {
		height: 100%;
		display: inline-flex;
		padding: 0.5rem 0;
		width: 2rem;
		pointer-events: all;
		cursor: grab;

		.grabbable-inner {
			height: 100%;
			border: 0.1rem outset var(--color-border-input);
			border-radius: 0 0.3rem 0.3rem 0;
			display: inline-flex;
			align-items: center;
			border-left: none;
			box-shadow: 0 0 0.4rem black;
			.dots {
				background-image: radial-gradient(circle, var(--color-border-input) 0.1rem, transparent 0.2rem);
				background-size: 100% 33.33%;
				height: 1.4rem;
				width: 0.6rem;
			}
		}
	}
}
</style>
